spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    username:
    password:
logging:
  level:
    root: warn
    com.usdj.database.dao: trace
  pattern:
    console: '%p%m%n'

